### ISSUE TITLE
Error `{}`

### ISSUE THREAD

**Issue by gossi** [figma/code-snippet-editor-plugin#10] opened 2024-01-30 14:12 UTC
I'm running into an issue and this might be because I'm using this plugin wrong and then this is a question to use it correctly - or - if I'm using the plugin correctly, then I likely found a bug.

What I see:

<img width="396" alt="Bildschirmfoto 2024-01-30 um 15 07 11" src="https://github.com/figma/code-snippet-editor-plugin/assets/283700/cb39ac56-7b4a-47d3-8b6c-d5a3f557b3d3">

Repro Steps:

A) In my components file:

- I did a couple of instances of my components with varying properties
- I went into devMode, selected the component
- Opened the code snippet editor
- Entered my snippet, selected the syntax and tested these on my instance to check if it works - it does and hell ya! I like it
- I removed the instances
- I published the component under assets

B) I another file:

- I use the asset panel to pull in the component
- I switched to devMode
- I see the error above

Expectation:

I would see the code in my other file as I'd seen this for the instances I tested them with in the same file.

**Comment by jake-figma** [comment] 2024-01-31 00:40
let me see if i can't repro. thanks for reporting.

**Comment by jake-figma** [comment] 2024-02-05 19:05
I am unable to reproduce and can successfully see code snippets for published library components. Is it possible you didn't update the library in the second file?

The fact that this says "error" in the title is a little confusing to me, unsure how that can happen at a code level. Does a red message pop up in Figma / are there errors in the JS console?
![CleanShot 2024-02-05 at 13 02 50](https://github.com/figma/code-snippet-editor-plugin/assets/97200987/4867ebb5-e0a7-490b-8536-574c818f2e60)


EDIT: I suppose another scenario would be if you added the template to the instance instead of the main component. You can add a template to any node, including an instance. If you want to have it stored in the library itself, you want to make sure youre adding the template to the main component / component set, not the instance.

**Comment by jake-figma** [comment] 2024-02-05 20:35
Able to repro the "error" state, but by doing something else entirely. Looking into this now!

**Comment by jake-figma** [comment] 2024-02-05 20:40
I believe this occurs when what was saved to plugin data wasnt a valid `CodegenResult[]` template array. I am going to write a guard on that.

**Comment by jake-figma** [comment] 2024-02-05 23:58
can confirm that this is actually my generic guard whenever an error happens. going to add a line that logs errors in the console/code so that we can debug.

**Comment by jake-figma** [comment] 2024-02-06 00:03
can you try and repro and see what shows up in the code panel now? commit: https://github.com/figma/code-snippet-editor-plugin/commit/37fa6adbc557e1ef9d9bb6bc3cf65d236518a069 should yield more information in the code snippet area now.

**Comment by gossi** [comment] 2024-02-06 09:55
It shows the code again in the inspect panel. Thanks a lot.

Here is a screenshot of the console from Figma. But its also a series of logs I see (like double entries).

<img width="345" alt="Bildschirmfoto 2024-02-06 um 10 52 20" src="https://github.com/figma/code-snippet-editor-plugin/assets/283700/c265bbc1-f4fc-4f26-9175-1f517453788f">

I opened both:

<img width="1292" alt="Bildschirmfoto 2024-02-06 um 10 50 50" src="https://github.com/figma/code-snippet-editor-plugin/assets/283700/5ec00755-f9e1-4b0c-b3e8-9d71ad255deb">

Here is the code snippet definition for that component:

<img width="559" alt="Bildschirmfoto 2024-02-06 um 10 54 25" src="https://github.com/figma/code-snippet-editor-plugin/assets/283700/2a3a2409-fe58-4a8a-9cd9-e3d3af864382">

PS. What I was seeing (didn't take a screenshot here). When inspecting the component, then it showed in a green alert, that something with regards to the code snippet was updated and I either x'ed it away or said ok.

**Comment by jake-figma** [comment] 2024-02-07 21:58
Ok so I am hearing that it sounds like this is resolved? If so I'll close this issue.

Two things: 
- I accidentally left some console statements in when i published, and just pulled those out of the code. thanks for bringing it to my attention, those will disappear next time i publish the plugin.
- while i was testing, i saw `<Lal @foo={{t ".." }}/>` isn't escaped, so I tested it escaped, `<Lal @foo=\{{t ".." }}/>` and it's still not rendering. I am going to create a new bug for that and try and get to the bottom of it.

**Comment by gossi** [comment] 2024-02-08 09:01
Awesome, great job! Thanks a lot

**Closed as completed** 2024-02-08 18:32 UTC
Labels: bug
